### ISSUE TITLE
Nothing  shows on command line when typing a function or an argument

### ISSUE THREAD

**Issue by papamarfo** [rpip/plex#14]
There appear to be a problem when typing a function or an argument into the terminal. You only get to see what you typed when you hit ctr+c.

**Comment by rpip** [comment]
Which operating system are you on? 

Can you share some screenshots?

**Comment by papamarfo** [comment]
I upgraded to windows 10 this morning from windows 7. Works well in 10 but after typing in a function or type in a text nothing shows up.  See the attached image.
![plex](https://cloud.githubusercontent.com/assets/6436250/14619666/52120c4e-056d-11e6-9890-7e4bba7fcbe0.PNG)

**Comment by rpip** [comment]
Pull the latest commits and rebuild.

For now, it just parses the code and prints the code structure (AST), so you see something like this:

```
plex (1)> let ama = ama with {age=18}
{:ok, [{:let, 1, {:identifier, 1, :ama}, {:identifier, 1, :ama}, {:record, 1, [{{:identifier, 1, :age}, {:integer, 1, 18}}]}, :undefined}]}
plex (2)>
```

Will soon start work on evaluation.

**Comment by rpip** [comment]
@manfordbenjamin Plex can now evaluate expressions. Unfortunately, I don't have time for Windows-specific issues now. If you're free to work on that, that'd be nice!
